// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as formatters from 'evolution-common/lib/utils/formatters';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';

export const household_size: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.size',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.size'),
    valueRange: {
        min: 1,
        max: 6
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.householdSizeValidation
};

export const home_income: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'household.income',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.income'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const household_carNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.carNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.carNumber'),
    valueRange: {
        min: 0,
        max: 5
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.carNumberValidation
};

export const home_ownership: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'home.ownership',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:home.ownership'),
    choices: choices.householdOwnershipChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const home_address: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.address',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:home.address'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const home_city: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.city',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:home.city'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const home_region: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.region',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:home.region'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const home_country: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.country',
    twoColumns: false,
    containsHtml: true,
    defaultValue: 'Canada',
    label: (t: TFunction) => t('home:home.country'),
    conditional: customConditionals.hiddenWithCanadaAsDefaultValueCustomConditional,
    validations: validations.requiredValidation
};

export const home_postalCode: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.postalCode',
    twoColumns: false,
    containsHtml: true,
    inputFilter: formatters.canadianPostalCodeFormatter,
    label: (t: TFunction) => t('home:home.postalCode'),
    conditional: defaultConditional,
    validations: validations.postalCodeValidation
};

export const home_geography = customWidgets.home_geography;

export const home_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'home.save',
    label: (t: TFunction) => t('home:home.save')
};
