import { checkConditionals } from 'evolution-common/lib/services/widgets/conditionals/checkConditionals';
import { type WidgetConditional } from 'evolution-common/lib/services/questionnaire/types';
import { getCurrentCarId } from './customHelpers';

// The conditionals generated by the generator are hardcoded to use the person id, so we need to make the conditionals for the engine type custom and change them to the car id.
// Also note that the car category and engine type choices were taken from the following page: https://carcosts.caa.ca/
export const ifEngineTypeIsGasCustomConditional: WidgetConditional = (interview, path) => {
    const currentCarId = getCurrentCarId({ interview, path }); // Get the current car id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryPickup'
            }
        ]
    });
};

export const ifEngineTypeIsHybridCustomConditional: WidgetConditional = (interview, path) => {
    const currentCarId = getCurrentCarId({ interview, path }); // Get the current car id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryPickup'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryCargoVan'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'cargoVan'
            }
        ]
    });
};

export const ifEngineTypeIsPluginHybridCustomConditional: WidgetConditional = (interview, path) => {
    const currentCarId = getCurrentCarId({ interview, path }); // Get the current car id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryPickup'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'pickup'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryCargoVan'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'cargoVan'
            }
        ]
    });
};

export const ifEngineTypeIsElectricCustomConditional: WidgetConditional = (interview, path) => {
    const currentCarId = getCurrentCarId({ interview, path }); // Get the current car id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'luxuryCargoVan'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'cargoVan'
            },
            {
                logicalOperator: '&&',
                path: `cars.information.${currentCarId}.category`,
                comparisonOperator: '!==',
                value: 'minivan'
            }
        ]
    });
};

// Don't show Question and give 'Québec' as default value
export const hiddenWithQuebecAsDefaultValueCustomConditional: WidgetConditional = (_interview) => {
    return [false, 'Québec'];
};

// Don't show Question and give 'Canada' as default value
export const hiddenWithCanadaAsDefaultValueCustomConditional: WidgetConditional = (_interview) => {
    return [false, 'Canada'];
};
