// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customWidgets from './customWidgets';

export const householdIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'householdIntro',
    containsHtml: true,
    text: (t: TFunction) => t('household:householdIntro'),
    conditional: defaultConditional
};

export const householdMembers = customWidgets.householdMembers;

export const personAge: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'age',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:age', {
            count: countPersons
        });
    },
    conditional: defaultConditional,
    validations: validations.ageValidation
};

export const personDrivingLicenseOwnership: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'drivingLicenseOwnership',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:drivingLicenseOwnership'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.ifAge16OrMoreConditional,
    validations: validations.requiredValidation
};

export const household_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'household.save',
    label: (t: TFunction) => t('household:household.save')
};
