// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customWidgets from './customWidgets';

export const carsIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'carsIntro',
    containsHtml: true,
    text: (t: TFunction) => t('cars:carsIntro'),
    conditional: defaultConditional
};

export const carInformation = customWidgets.carInformation;

export const carNickname: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'nickname',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('cars:nickname'),
    conditional: conditionals.if2OrMoreCarsConditional,
    validations: validations.requiredValidation
};

export const carCategory: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'category',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('cars:category'),
    choices: choices.carCategoryChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const carEngineType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'engineType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('cars:engineType'),
    choices: choices.carEngineChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const cars_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'cars.save',
    label: (t: TFunction) => t('cars:cars.save')
};
